# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
     defaultZone: http://user:password@localhost:1111/eureka/

  instance:
    preferIpAddress: true
    #server ip address
    ip-address: localhost

# HTTP Server
server:
  context-path: /products
  port: ${PRODUCTS_SERVICE_PORT}   # HTTP (Tomcat) port
  #server ip address
  #address: 127.0.0.1
  tomcat:
    max-threads: 500
    
logging:
  level:
    com.netflix.discovery.TimedSupervisorTask: "OFF"